### PR TITLE
refactor(ui): refactor listitem, set img aspect ratio and add new fonts

### PR DESCRIPTION
**Pull request by olros**
Lint, test and build
## Description

Comments/issues/screenshots:
- Listitem almost don't use media query anymore, so it can be used in narrow div's easier
- Listitem uses less space
- New Listitem which takes entire Event, News and JobPost-items so it can be modified one place
- Fix all images at aspect ratio: 21/9
- Add new fonts to headers
- Create a new layout in News-overview with grid
- Flatten out some components

image
image
image

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] The PR includes a `closes #issueID`
- [x] The PR includes a picture showing visual changes

## Typescript convert checklist

- [x] All relative imports has been converted to absolute imports
- [x] All HOC's have been replaced with Hooks
- [x] Uses theme.spacing() instead of custom padding
- [x] Uses theme.breakpoints instead of custom media queries

### CODE REVIEW

**Comment by olros** [comment]
Fikser dette #262 @maxschau ? Har ikke safari så får ikke testet :(

**Comment by maxschau** [comment]
Fungerte ypperlig på safari @olros

**Comment by olros** [comment]
Strålende! Da legger vi til closes #262

**Comment by olros** [comment]
Strålende!
closes #262

**Review by Her0elt — APPROVED** [review]
looks good

**Pull request merged**
